### ISSUE TITLE
How to create SOAP request with CDATA

### ISSUE THREAD

**Issue by pzienowicz** [AlexGilleran/IceSoap#15]
Hi,

Is there any way to send eg. html code in CDATA tag?
When I add text node like this:
`<![CDATA[
        <Request>
           <Authentication CMId="68" Function="1" Guid="5594FB83-F4D4-431F-B3C5-EA6D7A8BA795" Password="poihg321TR"/>
           <Establishment Id="4297867"/>
        </Request>
        ]]>`

The problem is:
`<![CDATA[     ]]> `
is displaying like 
` &lt;![CDATA[ and ]]&gt;  `

Thanks!

**Comment by AlexGilleran** [comment]
I don't know of any way with the current API.

Looks like it's possible with XMLSerializer though, so it should be possible to add: https://developer.android.com/reference/org/xmlpull/v1/XmlSerializer.html#cdsect(java.lang.String)

**Comment by pzienowicz** [comment]
Could you provide me any example?
How can I use it with **com.alexgilleran.icesoap.envelope.impl.BaseSOAP11Envelope**?

**Comment by AlexGilleran** [comment]
I think you could create a `XMLCDataNode` class that extends `XMLTextNode`, and override [serializeContent](https://github.com/AlexGilleran/IceSoap/blob/master/IceSoap/src/com/alexgilleran/icesoap/xml/impl/XMLTextNodeImpl.java#L53) to use [XMLSerializer.cdsect(getValue())](https://developer.android.com/reference/org/xmlpull/v1/XmlSerializer.html#cdsect(java.lang.String)) instead of `XMLSerializer.text`. Then you could add it to any existing envelope or XMLNode with [addElement](https://github.com/AlexGilleran/IceSoap/blob/master/IceSoap/src/com/alexgilleran/icesoap/xml/XMLParentNode.java#L42)

**Comment by pzienowicz** [comment]
Works like a charm.
Thank you @AlexGilleran!

**Comment by AlexGilleran** [comment]
Yay! No worries :)
